services:
  web:
    container_name: nuxt-docker
    build:
      context: ./web
      dockerfile: Dockerfile.${BUILD_TARGET}
    ports:
      - "3000:3000"
    expose:
      - "3000"
    restart: unless-stopped
    volumes:
      - ./web:/app/
      - /app/.nuxt/
      - /app/.output/
      - /app/node_modules/
      - db-data:/app/storage
    tmpfs:
      - /tmp
    environment:
      - BUILD_TARGET=${BUILD_TARGET}
  scraper:
    container_name: scraper-docker
    build:
      context: ./scraper
      dockerfile: Dockerfile.${BUILD_TARGET}
    volumes:
      - ./scraper:/app/
      - db-data:/app/storage
    environment:
      - BUILD_TARGET=${BUILD_TARGET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
volumes:
  db-data: