FROM node:21.5.0 as build

WORKDIR /app
# copy over package.json files
COPY package*.json ./
# install all depencies
RUN npm ci && npm cache clean --force
# copy over all files to the work directory
COPY . .
# build the project
RUN npm run build

FROM node:21.5.0
WORKDIR /app
COPY package*.json .
COPY nuxt.config.ts .
COPY --from=build /app/.output ./.output
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/.nuxt ./.nuxt

# run the build project with node
ENTRYPOINT ["node", ".output/server/index.mjs"]
