FROM node:21.5.0

WORKDIR /app

# copy over package.json files
COPY package*.json /app/

# install all depencies
RUN npm install

# copy over all files to the work directory
COPY . .

# make script executable
RUN chmod +x /app/entry-dev.sh

# run the build project with node
ENTRYPOINT ["/app/entry-dev.sh"]